# Generated by Django 5.0.7 on 2024-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_certificate_filmwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfilmwork',
            name='gender',
            field=models.TextField(choices=[('male', 'male'), ('female', 'female')], null=True, verbose_name='gender'),
        ),
    ]
